Remove protobuf php ext
This ext for the PHP7.3 is causing an error when we try to send a
document to firestore

Error: "Segmentation fault (core dumped)"